package med.voll.api.domain.doctor;

public enum Specialty {
  ORTHOPEDICS,
  CARDIOLOGY,
  GYNECOLOGY,
  PEDIATRICS,
  DERMATOLOGY,
  NEUROLOGY,
  PSYCHIATRY,
  ENDOCRINOLOGY,
  UROLOGY,
  OPHTHALMOLOGY,
  GASTROENTEROLOGY,
  PULMONOLOGY
}
